### ISSUE TITLE
Because flutter_launcher_icons 0.9.0 depends on yaml ^3.0.0-nullsafety.0 

### ISSUE THREAD

**Issue by limsocheat** [daisuke-fukuda/flutter_launcher_name#12]
> Because flutter_launcher_icons 0.9.0 depends on yaml ^3.0.0-nullsafety.0 and every version of flutter_launcher_name depends on yaml ^2.1.16, flutter_launcher_icons 0.9.0 is incompatible with flutter_launcher_name.
> 
> So, because krudtep depends on both flutter_launcher_name 0.0.1 and flutter_launcher_icons 0.9.0, version solving failed.
> pub get failed (1; So, because krudtep depends on both flutter_launcher_name 0.0.1 and flutter_launcher_icons 0.9.0, version solving failed.)

**Comment by ride4sun** [comment]
@daisuke-fukuda could you please update this package and accept the outstanding pull requests. That would help to actually use this package. Thx

**Comment by ride4sun** [comment]
Does anybody have a git package I can reference in the meantime until this gets updated?

**Comment by ride4sun** [comment]
I just create one:
```
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "0.9.1"
```
