### ISSUE TITLE
Flavors

### ISSUE THREAD

**Issue by edgarfroes** [daisuke-fukuda/flutter_launcher_name#3]
This plugin should have support for Flavors.
App's name should respect different flavors, e.g. like so:

```
flutter_launcher_name:
  name: "yourNewAppLauncherName"
  flavor: dev
    name: "yourNewAppLauncherNameDev"
  flavor: staging
    name: "yourNewAppLauncherNameStaging"
  flavor: prod
    name: "yourNewAppLauncherName"
```
